// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_middleware from "./routes/(platform)/middleware.ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $CharacterForm from "./islands/CharacterForm.tsx";
import * as $Logout from "./islands/Logout.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/middleware.ts": $_platform_middleware,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharacterForm.tsx": $CharacterForm,
    "./islands/Logout.tsx": $Logout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
